### ISSUE TITLE
Error with Raspbian Jessie

### ISSUE THREAD

**Issue by schneil** [zombiekipling/solriv#2]
I've just upgraded my Raspberry Pi from Wheezy to Jessie.
With Wheezy the solriv script worked flawlessly.
However now I've uploaded to Jessie, it doesn't work.  Solriv.err records the following:
"Traceback (most recent call last):
  File "/home/pi/git/solriv/solriv.py", line 132, in <module>
    BroadcastMessage()
  File "/home/pi/git/solriv/solriv.py", line 26, in BroadcastMessage
    s.connect(("<broadcast>", UDPPORT))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 101] Network is unreachable"

The solriv script still works on my ubuntu laptop, so I know the inverter's still talking to the network.  Could you help? It would be a real chore to downgrade back to Wheezy!

**Comment by zombiekipling** [comment]
Sorry the very delayed response. I've updated the script to allow you to specify the IP address of your Pi as an optional parameter. Could you give it a try?

**Comment by schneil** [comment]
Hello
Thanks for getting back to me.  I'll put a Raspbian Jessie image on an SSD and let you know how I get on.I should mention I am very grateful for your hard work :)
Neil

```
  From: zombiekipling <notifications@github.com>
```

 To: zombiekipling/solriv solriv@noreply.github.com 
Cc: schneil schneil_2k@yahoo.co.uk
 Sent: Sunday, 3 January 2016, 21:58
 Subject: Re: [solriv] Error with Raspbian Jessie (#2)

Sorry the very delayed response. I've updated the script to allow you to specify the IP address of your Pi as an optional parameter. Could you give it a try?—

**Comment by schneil** [comment]
Hello
Just bought a Pi3 and installed Raspbian Jessie on it.The new script works great!

```
  From: zombiekipling <notifications@github.com>
```

 To: zombiekipling/solriv solriv@noreply.github.com 
Cc: schneil schneil_2k@yahoo.co.uk
 Sent: Sunday, 3 January 2016, 21:58
 Subject: Re: [solriv] Error with Raspbian Jessie (#2)

Sorry the very delayed response. I've updated the script to allow you to specify the IP address of your Pi as an optional parameter. Could you give it a try?—
